# Generated by Django 3.1.5 on 2021-09-05 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Gelen Mesaj', 'verbose_name_plural': 'Gelen Mesajlar'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='Adınız',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Soyadınız',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Telefonunuz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450, verbose_name='TESTİN adı')),
                ('tittle', models.CharField(max_length=450, verbose_name='TESTİN başlığı')),
                ('description', models.CharField(max_length=450, verbose_name='TESTİN açıklaması')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('testin_kategorisi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.category', verbose_name='TESTİN sınıfı')),
            ],
        ),
    ]
