# Generated by Django 3.1.5 on 2021-09-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210905_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Sınıf', 'verbose_name_plural': 'Sınıflar'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Testler'},
        ),
    ]
