# Generated by Django 3.1.5 on 2021-09-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210905_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(default='/media/default.gif', upload_to='images/', verbose_name='TESTİN göreseli'),
        ),
        migrations.AlterField(
            model_name='test',
            name='upload',
            field=models.FileField(upload_to='uploads/', verbose_name='TEST'),
        ),
    ]
