# Generated by Django 3.1.5 on 2021-09-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210905_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(default='images/deafult.gif', upload_to='images/', verbose_name='TESTİN göreseli'),
        ),
    ]
