# Generated by Django 3.1.5 on 2021-09-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210906_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='testin_kategorisi',
            new_name='category',
        ),
    ]
